FROM mcr.microsoft.com/devcontainers/universal:2

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
        curl \
        htop \
        openjdk-21-jre \
        tree