github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false

image: chriswyatt/seqeratraining

tasks:
  - name: Prepare Nextflow Tutorial
    init: |
      gp ports await 23000 && gp preview https://training.seqera.io
      unset JAVA_TOOL_OPTIONS
      clear
    command: |
      docker pull nextflow/rnaseq-nf
      cd nf-training
