github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false

image:
  file: nfcore/gitpod:latest

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start web server
    command: gp await-port 23000 && gp preview https://training.seqera.io    

#  - name: Download Nextflow Tutorial
#    init: |
#      echo 'init script' # runs during prebuild
#      
#    command: |
#      cd nf-training
#      curl -s https://get.nextflow.io | bash
#      chmod +x nextflow
#      sudo mv nextflow /usr/local/bin/
#      docker pull nextflow/rnaseq-nf
#      alias conda_activate=". /opt/conda/etc/profile.d/conda.sh; conda activate base"
#      unset JAVA_TOOL_OPTIONS
