github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start web server
    command: gp await-port 23000 && gp preview https://training.seqera.io  
  - name: Download Nextflow Tutorial
    init: |
      echo 'init script' # runs during prebuild
      echo 'start script'
      curl -s https://get.nextflow.io | bash
      mkdir /workspace/bin
    command: |
      cp ./nextflow /workspace/bin/nextflow  
      export PATH=/workspace/bin:$PATH

      

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
