INHERIT: ../en/mkdocs.yml
theme:
  language: de
  custom_dir: ../en/overrides
extra:
  consent:
    title: "Cookie-Zustimmung"
    description: >-
      Wir verwenden Cookies, um Ihre wiederholten Besuche und Präferenzen zu erkennen
      sowie die Effektivität unserer Dokumentation zu messen und festzustellen, ob
      Benutzer*innen finden, wonach sie suchen. Mit Ihrer Zustimmung helfen Sie uns,
      unsere Schulungsmaterialien zu verbessern.
      Erfahren Sie mehr darüber,
      <a href="https://seqera.io/privacy-policy/#cookies" target="_blank" rel="noopener">wie wir Cookies verwenden</a>.
    cookies:
      posthog: "PostHog Analytics"
  nav_group_labels:
    "Schulungsumgebung": "Einrichtung & Hilfe"
    "Nextflow Run": "Nutzer*innen"
    "Hello Nextflow": "Entwickler*innen"
  nav_title_overrides:
    nextflow_run/index.md: Nextflow Run
    nfcore_run/index.md: Run nf-core
    seqera_run/index.md: Run with Seqera
    hello_nextflow/index.md: Hello Nextflow
    hello_nf-core/index.md: Build with nf-core
    nf4_science/index.md: "Nextflow für die Wissenschaft"
    side_quests/index.md: "Side Quests"
    envsetup/index.md: "Schulungsumgebung"
  nav_child_title_overrides:
    nextflow_run/index.md: "Überblick"
    nfcore_run/index.md: "Überblick"
    seqera_run/index.md: "Überblick"
    hello_nextflow/index.md: "Überblick"
    hello_nf-core/index.md: "Überblick"
    nf4_science/index.md: "Überblick"
    nf4_science/genomics/index.md: "Überblick"
    nf4_science/rnaseq/index.md: "Überblick"
    nf4_science/imaging/index.md: "Überblick"
    side_quests/index.md: "Überblick"
  nav_section_separators:
    side_quests/dev_environment/index.md: "Entwickler-Tools & Tricks"
    side_quests/working_with_files/index.md: "Vertiefung in den Datenfluss"
    side_quests/workflows_of_workflows/index.md: "Modulare Architektur in Aktion"
    side_quests/nf_test/index.md: "Das erweiterte Nextflow-Universum"
