= Environment setup

Nextflow can be used on any POSIX compatible system (Linux, OS X, Windows Subsystem for Linux etc.).

*Requirements*:

* Bash
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 8 (or later, up to 15)]

To check your java version : `java -version`

*Optional requirements*:

* https://www.docker.com/[Docker] engine 1.10.x (or later)
* https://github.com/sylabs/singularity[Singularity] 2.5.x (or later)
* https://conda.io/[Conda] 4.5 (or later)
* http://www.graphviz.org/[Graphviz] 
* https://aws.amazon.com/cli/[AWS CLI]
* AWS Batch computing environment configured 

== Local installation

We recommend using the AWS cloud9 environment for this tutorial (see later), yet if you wish to run locally, follow these instructions:

=== Download Nextflow:

Enter this command in your terminal:

----
wget -qO- https://get.nextflow.io | bash
----

Or, if you prefer curl: 

----
curl -s https://get.nextflow.io | bash
----

Then ensure that the downloaded binary is executable:

----
chmod +x nextflow
----

or put the nextflow executable into your $PATH (e.g. /usr/bin)

=== Training material 

Download the training material by copy & pasting the following command 
in the terminal:

[source,bash,linenums]
----
curl https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

Or alternatively if you have `wget` instead of curl:

[source,bash,linenums]
----
wget -q -O- https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

== Setup with AWS Cloud9

If you are running this tutorial in an AWS Cloud9 environment, 
first login to AWS following the details in the spreadsheet (with the given IAM user account ID, name and password)

WARNING: Make sure you logout of any previously open cloud9 sessions first.

Then click openIDE, to enter the AWS environment.

=== Training material 

Download the training material by copy & pasting the following command 
in the terminal:

[source,bash,linenums]
----
curl https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

Or alternatively if you have `wget` instead of curl:

[source,bash,linenums]
----
wget -q -O- https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

then run the following one-liner to setup the virtual environment (this takes ~3 minutes): 

[source,bash,linenums]
----
source setup/all.sh
----

=== Nextflow installation 

Install the latest version of Nextflow by copy & pasting the following 
snippet in a terminal window: 

[source,bash,linenums]
----
curl get.nextflow.io | bash
mv nextflow ~/bin
----

Check Nextflow has installed correctly by running the following command: 

[source,bash,linenums]
----
nextflow info
----

You should see the following (or similar):

[source,bash]
----
  Version: 21.10.6 build 5660
  Created: 21-12-2021 16:55 UTC 
  System: Linux 4.14.262-135.489.amzn1.x86_64
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 1.8.0_312-b07
  Encoding: UTF-8 (UTF-8)
----

== Selecting a Nextflow version

By default Nextflow will pull the latest stable version into your environment.

However, Nextflow is constantly evolving as we make improvements and fix bugs.

It is worth checking out the latest releases on github: https://github.com/nextflow-io/nextflow[(click here)].

If you want or need to use a specific version of Nextflow, you can set the NXF_VER variable as so:

[source,bash,linenums]
----
export NXF_VER=21.10.0
----

Then run `nextflow -version` to make sure that the change has taken effect.

