= Environment setup

== Local installation

Nextflow can be used on any POSIX compatible system (Linux, OS X, Windows Subsystem for Linux etc.).

*Requirements*:

* Bash
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 8 (or later, up to 15)]

*Optional requirements*:

* https://www.docker.com/[Docker] engine 1.10.x (or later)
* https://github.com/sylabs/singularity[Singularity] 2.5.x (or later)
* https://conda.io/[Conda] 4.5 (or later)
* http://www.graphviz.org/[Graphviz] 
* https://aws.amazon.com/cli/[AWS CLI]
* AWS Batch computing environment configured 

To check you java version : `java -version`

=== Download Nextflow:

Enter this command in your terminal:

----
wget -qO- https://get.nextflow.io | bash
----

Or, if you prefer curl: 

----
curl -s https://get.nextflow.io | bash
----

Then ensure that the downloaded binary is executable:

----
chmod +x nextflow
----

or put the nextflow executable into your $PATH (e.g. /usr/bin)

=== Training material 

Download the training material by copy & pasting the following command 
in the terminal:

[source,bash,linenums]
----
curl https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

Or alternatively if you have `wget` instead of curl:

[source,bash,linenums]
----
wget -q -O- https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

== Setup with AWS Cloud9

If you are running this tutorial in an AWS Cloud9 environment, 
run the following one-liner to setup the virtual environment: 

[source,bash,linenums]
----
source setup/all.sh
----

=== Nextflow installation 

Install the latest version of Nextflow by copy & pasting the following 
snippet in a terminal window: 

[source,bash,linenums]
----
curl get.nextflow.io | bash
mv nextflow ~/bin
----

Check the correct installation running the following command: 

[source,bash,linenums]
----
nextflow info
----

== Selecting Nextflow version

By default Nextflow will pull the latest stable version into your environment.

However, Nextflow is constantly evolving as we make improvements and fix bugs.

It is worth checking out the latest releases on github: https://github.com/nextflow-io/nextflow[(click here)].

If you want or need to use a specific version of Nextflow, you can set the NXF_VER variable as so:

[source,bash,linenums]
----
export NXF_VER=21.10.0
----

Then run `nextflow -version` to make sure that the change has taken effect.

