= Environment setup

== Using Gitpod (the simplest way)

Here we setup Nexflow, dependencies and the training documents on a web based compute environment using Gitpod. 

**First**: if you haven't got a **Github** account, please sign up https://github.com/[here].

**Second**: Simply enter the following URL in your web browser (ideally: Firefox, Google Chrome):
https://gitpod.io/#https://github.com/chriswyatt1/Gitpod_test

Now you should have all the training documents, Nextflow and other dependencies installed into a Gitpod environment. You have 50 hours of Gitpod usage per month, where all the computation is happening in the cloud, once you close the terminal it will delete your session.

== Using your terminal 

Nextflow can be used on any POSIX compatible system (Linux, OS X, etc.).

It requires Bash and http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 8 (or later, up to 15)] to be installed.

Optional requirements for this workshop:

* https://www.docker.com/[Docker] engine 1.10.x (or later)
* https://github.com/sylabs/singularity[Singularity] 2.5.x (or later)
* https://conda.io/[Conda] 4.5 (or later)
* http://www.graphviz.org/[Graphviz] 
* https://aws.amazon.com/cli/[AWS CLI] 
* AWS Batch computing environment properly configured 


=== Setup AWS Cloud9 environment (Optional) 

Only if you are running this tutorial in the AWS Cloud9 environment, 
run the following one-liners to properly setup the required dependencies: 

[source,bash,linenums]
----
source setup/all.sh
----

=== Training material 

Download the training material by copy & pasting the following command 
in the terminal:

[source,bash,linenums]
----
curl https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

Or alternatively if you have `wget` instead of curl:

[source,bash,linenums]
----
wget -q -O- https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

=== Nextflow installation 

Install the latest version of Nextflow by copy & pasting the following 
snippet in a terminal window: 

[source,bash,linenums]
----
curl get.nextflow.io | bash
mv nextflow ~/bin
----

Check the correct installation running the following command: 

[source,bash,linenums]
----
nextflow info
----
