= Environment setup

== Requirements

Nextflow can be used on any POSIX compatible system (Linux, OS X, etc.).
It requires Bash and
http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java
8 (or later, up to 15)] to be installed.

Optional requirements for this workshop:

* https://www.docker.com/[Docker] engine 1.10.x (or later)
* https://github.com/sylabs/singularity[Singularity] 2.5.x (or later, optional)
* https://conda.io/[Conda] 4.5 (or later, optional)
* http://www.graphviz.org/[Graphviz] (optional)
* https://aws.amazon.com/cli/[AWS CLI] (optional)
* AWS Batch computing environment properly configured (optional)



== Training material 

Download the training material copy & pasting the following command 
in the terminal:

[source,bash,linenums]
----
curl https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----

Or in alternative if you have `wget` instead of curl:

[source,bash,linenums]
----
wget -q -O- https://s3-eu-west-1.amazonaws.com/seqeralabs.com/public/nf-training.tar.gz | tar xvz
----


== Setup AWS Cloud9 environment (Optional) 

Only if you are running this tutorial in the AWS Cloud9 environment, 
run the following one-liners to properly setup the required dependencies: 

[source,bash,linenums]
----
source setup/all.sh
----

== Nextflow installation 

Install the latest version of Nextflow copy & pasting the following 
snippet in a terminal window: 

[source,bash,linenums]
----
curl get.nextflow.io | bash
mv nextflow ~/bin
----

Check the correct installation running the following command: 

[source,bash,linenums]
----
nextflow info
----
