= Welcome to the Nextflow Training Workshop

We are excited to have you on the path to writing reproducible and scalable scientific workflows using Nextflow. This guide complements the full Nextflow documentation - if you ever have any doubts, head over to the docs located https://www.nextflow.io/docs/latest[here].

By the end of this course you should:

1. Be proficient in writing Nextflow pipelines
2. Know the basic Nextflow concepts of Channels, Processes and Operators
3. Have an understanding of containerised workflows
4. Understand the different execution platforms supported by Nextflow 
5. Be introducted to the Nextflow community and ecosystem

= Overview

To get you started with Nextflow as quickly as possible, we will walk through the following steps:

1. Set up a development environment to run Nextflow. 

2. Explore Nexflow concepts using some basic workflows including a multistep RNA-Seq analysis. 

3. Built and use Docker containers to encaspusulate all workflow dependencies. 

4. Dive deeper into the core Nextflow syntax including Channels, Processes and Operators. 

5. Cover cluster and cloud deployment scenarios and explore Nextflow Tower capabilities. 

This should give you a great basis to start writing your own pipelines and to understand the possibilities that Nextflow provides. We hope you enjoy the course! This is ever-evolving document and feedback is always welcome.

= Summary

1. <<Environment setup>>
2. <<Introduction>>
3. <<Simple RNA-Seq pipeline>>
4. <<Manage dependencies & containers>>
5. <<Channels>>
6. <<Processes>>
7. <<Operators>>
8. <<Groovy basic structures and idioms>>
9. <<DSL2 and modules>>
10. <<Get started with Nextflow Tower>>
11. <<Nextflow configuration>>
12. <<Deployment scenarios>>
13. <<Execution cache and resume>>
14. <<Error handling & troubleshooting>>

