[discrete]
=== Welcome to the Nextflow Training Workshop

We are excited to have you on the path to writing reproducible and scalable scientific workflows using Nextflow. This guide complements the full Nextflow documentation - if you ever have any doubts, head over to the docs located https://www.nextflow.io/docs/latest[here].

By the end of this course you should:

1. Be proficient in writing Nextflow pipelines
2. Know the basic Nextflow concepts of Channels, Processes and Operators
3. Have an understanding of containerized workflows
4. Understand the different execution platforms supported by Nextflow
5. Be introduced to the Nextflow community and ecosystem

[discrete]
=== Overview

To get you started with Nextflow as quickly as possible, we will walk through the following steps:

1. Set up a development environment to run Nextflow

2. Explore Nextflow concepts using some basic workflows, including a multi-step RNA-Seq analysis

3. Build and use Docker containers to encapsulate all workflow dependencies

4. Dive deeper into the core Nextflow syntax including Channels, Processes and Operators

5. Cover cluster and cloud deployment scenarios and explore Nextflow Tower capabilities

This will give you a broad understanding of Nextflow so that you can start writing your own pipelines. We hope you enjoy the course! This is an ever-evolving document and feedback is always welcome.

[discrete]
=== Summary

1. <<Environment setup>>
2. <<Introduction>>
3. <<Simple RNA-Seq pipeline>>
4. <<Manage dependencies and containers>>
5. <<Channels>>
6. <<Processes>>
7. <<Operators>>
8. <<Groovy basic structures and idioms>>
9. <<Modularization>>
10. <<Nextflow configuration>>
11. <<Deployment scenarios>>
12. <<Get started with Nextflow Tower>>
13. <<Execution cache and resume>>
14. <<Error handling and troubleshooting>>

