INHERIT: ../en/mkdocs.yml
theme:
  language: ko
  custom_dir: ../en/overrides
extra:
  consent:
    title: "쿠키 동의"
    description: >-
      저희는 귀하의 반복 방문과 선호도를 인식하고, 문서의 효과성과 사용자가
      원하는 정보를 찾고 있는지 측정하기 위해 쿠키를 사용합니다. 동의해 주시면
      교육 자료를 개선하는 데 도움이 됩니다.
      <a href="https://seqera.io/privacy-policy/#cookies" target="_blank" rel="noopener">쿠키 사용 방법</a>에 대해 자세히 알아보세요.
    cookies:
      posthog: "PostHog 분석"
  nav_group_labels:
    "교육 환경": "설정 및 도움말"
    "Nextflow Run": "사용자"
    "Hello Nextflow": "개발자"
  nav_title_overrides:
    nextflow_run/index.md: Nextflow Run
    nfcore_run/index.md: Run nf-core
    seqera_run/index.md: Run with Seqera
    hello_nextflow/index.md: Hello Nextflow
    hello_nf-core/index.md: Build with nf-core
    nf4_science/index.md: "과학을 위한 Nextflow"
    side_quests/index.md: "사이드 퀘스트"
    envsetup/index.md: "교육 환경"
  nav_child_title_overrides:
    nextflow_run/index.md: "개요"
    nfcore_run/index.md: "개요"
    seqera_run/index.md: "개요"
    hello_nextflow/index.md: "개요"
    hello_nf-core/index.md: "개요"
    nf4_science/index.md: "개요"
    nf4_science/genomics/index.md: "개요"
    nf4_science/rnaseq/index.md: "개요"
    nf4_science/imaging/index.md: "개요"
    side_quests/index.md: "개요"
  nav_section_separators:
    side_quests/dev_environment/index.md: "개발자 도구 및 팁"
    side_quests/working_with_files/index.md: "데이터 흐름 심층 분석"
    side_quests/workflows_of_workflows/index.md: "실전 모듈형 아키텍처"
    side_quests/nf_test/index.md: "Nextflow 확장 유니버스"
