INHERIT: ../en/mkdocs.yml
edit_uri: edit/master/docs/tr/docs/
theme:
  language: tr
  custom_dir: ../en/overrides
extra:
  consent:
    title: "Çerez Onayı"
    description: >-
      Tekrarlayan ziyaretlerinizi ve tercihlerinizi tanımak, dokümantasyonumuzun
      etkinliğini ölçmek ve kullanıcıların aradıklarını bulup bulmadığını belirlemek
      için çerezler kullanıyoruz. Onayınızla eğitim materyallerimizi geliştirmemize
      yardımcı oluyorsunuz.
      <a href="https://seqera.io/privacy-policy/#cookies" target="_blank" rel="noopener">Çerezleri nasıl kullandığımız</a> hakkında daha fazla bilgi edinin.
    cookies:
      posthog: "PostHog Analytics"
  nav_group_labels:
    "Eğitim Ortamı": "Kurulum ve Yardım"
    "Nextflow Run": "Kullanıcılar"
    "Hello Nextflow": "Geliştiriciler"
  nav_title_overrides:
    nextflow_run/index.md: Nextflow Run
    nfcore_use/index.md: Use nf-core
    seqera_scale/index.md: Scale with Seqera
    hello_nextflow/index.md: Hello Nextflow
    nfcore_build/index.md: Build with nf-core
    nf4_science/index.md: "Bilim için Nextflow"
    nf4_science/genomics/index.md: "Genomik"
    nf4_science/rnaseq/index.md: "RNAseq"
    nf4_science/imaging/index.md: "Görüntüleme"
    side_quests/index.md: "Yan Görevler"
    envsetup/index.md: "Eğitim Ortamı"
  nav_child_title_overrides:
    nextflow_run/index.md: "Genel Bakış"
    nfcore_use/index.md: "Genel Bakış"
    seqera_scale/index.md: "Genel Bakış"
    config_exec/index.md: "Genel Bakış"
    hello_nextflow/index.md: "Genel Bakış"
    nfcore_build/index.md: "Genel Bakış"
    nf4_science/index.md: "Genel Bakış"
    nf4_science/genomics/index.md: "Genel Bakış"
    nf4_science/rnaseq/index.md: "Genel Bakış"
    nf4_science/imaging/index.md: "Genel Bakış"
    side_quests/index.md: "Genel Bakış"
  nav_section_separators:
    side_quests/dev_environment/index.md: "Geliştirici Araçları ve İpuçları"
    side_quests/working_with_files/index.md: "Veri Akışına Derinlemesine Bakış"
    side_quests/workflows_of_workflows/index.md: "Modüler Mimari Uygulamada"
    side_quests/nf_test/index.md: "Nextflow'un Genişletilmiş Evreni"
