INHERIT: ../en/mkdocs.yml
theme:
  language: tr
  custom_dir: ../en/overrides
extra:
  consent:
    title: "Çerez Onayı"
    description: >-
      Tekrarlayan ziyaretlerinizi ve tercihlerinizi tanımak, dokümantasyonumuzun
      etkinliğini ölçmek ve kullanıcıların aradıklarını bulup bulmadığını belirlemek
      için çerezler kullanıyoruz. Onayınızla eğitim materyallerimizi geliştirmemize
      yardımcı oluyorsunuz.
      <a href="https://seqera.io/privacy-policy/#cookies" target="_blank" rel="noopener">Çerezleri nasıl kullandığımız</a> hakkında daha fazla bilgi edinin.
    cookies:
      posthog: "PostHog Analytics"
  nav_group_labels:
    "Eğitim Ortamı": "Kurulum ve Yardım"
    "Nextflow Run": "Kullanıcılar"
    "Hello Nextflow": "Geliştiriciler"
  nav_title_overrides:
    nextflow_run/index.md: Nextflow Run
    nfcore_run/index.md: Run nf-core
    seqera_run/index.md: Run with Seqera
    hello_nextflow/index.md: Hello Nextflow
    hello_nf-core/index.md: Build with nf-core
    nf4_science/index.md: "Bilim için Nextflow"
    side_quests/index.md: "Yan Görevler"
    envsetup/index.md: "Eğitim Ortamı"
