# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "COWPY"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "cowpy":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: null
      identifier: null

input:
  - - meta:
        type: map
        description: Groovy Map containing sample information. e.g. `[
          id:'sample1' ]`
    - input:
        type: file
        description: ""
        pattern: ""
        ontologies:
          - edam: ""
output:
  output:
    - - meta:
          type: map
          description: Groovy Map containing sample information. e.g. `[
            id:'sample1' ]`
      - "*":
          type: file
          description: ""
          pattern: ""
          ontologies:
            - edam: ""
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@example"
maintainers:
  - "@example"
