# Build and push the Docker image for building the site (mkdocs material)

name: Build Docker [MkDocs]

on:
  pull_request:
    paths:
      - ".github/mkdocs.Dockerfile"
      - ".github/workflows/docker-mkdocs.yml"
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  mkdocs_docker:
    if: github.repository == 'nextflow-io/training'
    name: Build + push mkdocs docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build / push latest image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          file: .github/mkdocs.Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/nextflow-io/training-mkdocs:latest
