name: Publish docs [dev]

on:
  release:
    types: [published]
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.6

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build Docs Website
        run: mike deploy --push --alias-type copy --update-aliases 0.dev development
